name: assignment
description: "Grocery Shop Application for Shop Owners and Customers"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  geolocator: ^13.0.2
  uuid: ^4.5.1
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/candy/
    - images/coffee/
    - images/corn/
    - images/fish/
    - images/rice/
